### ISSUE TITLE
can't install in ubuntu

### ISSUE THREAD

**Issue by dronmoroz** [L-Leite/cso2-master-services#11]
Hello. When I start command ./setup_services.sh I get following errors:
![image](https://user-images.githubusercontent.com/14977332/58329624-aeaa1e00-7e3d-11e9-88cc-8d1fa615e503.png)
I'm using Ubuntu 18.04

**Comment by dronmoroz** [comment]
Any solution? :(

**Comment by felixabi** [comment]
I get error too 
![8888888888888888](https://user-images.githubusercontent.com/36341134/58816130-825a8280-8631-11e9-9f13-c8cc58ee4125.PNG)

**Comment by L-Leite** [comment]
Fixed in commit 992946a
