### ISSUE TITLE
can't install in centos

### ISSUE THREAD

**Issue by felixabi** [L-Leite/cso2-master-services#12]
![1](https://user-images.githubusercontent.com/36341134/58707988-25579600-83bf-11e9-81d5-fadf54c9e9a8.PNG)

? ./setup_services.sh install errror*

**Comment by Ochii** [comment]
Install git

**Comment by felixabi** [comment]
This time I've installed ubuntu I get this error.

>Node JS [OK]
>Git [Ok]
>TaR [Ok]
>cURL [Ok]

Now: [  Ubuntu 16.4  ]- 64 it

![8888888888888888](https://user-images.githubusercontent.com/36341134/58816263-d49ba380-8631-11e9-922f-ddd857815d20.PNG)

**Comment by L-Leite** [comment]
Fixed in 992946a
