### ISSUE TITLE
Unimplemented/Missing features

### ISSUE THREAD

**Issue by cso2** [L-Leite/cso2-master-services#17]
a change in the back of the lobby

Denial message output when entering a room full of room personnel.

Unable to expel users (you cannot expel them even if you press X next to the game start player in the room)

Add friends, Banlist function 

which server you are.Not marked which room it is in. (Currently marked as %s1>Room%s2)

Clan

Decomposition, combination (I think it is a function that I don't need personally, but infinite loading occurs when I use it now.)

cso2-master-server or missing functions mentioned in the project were excluded.

Can anyone tell you any other missing function?

**Comment by felixabi** [comment]
clan is missing

**Comment by DebugBios** [comment]
Nickname change item

Remove from inventory when using consumable items

**Comment by DebugBios** [comment]
Point, Cash

**Comment by ghost** [comment]
Room Information

![10](https://user-images.githubusercontent.com/44349391/93339756-ed4fbd00-f866-11ea-8a5e-de411ca4ed1a.PNG)
