### ISSUE TITLE
Merging all the services repositories into one?

### ISSUE THREAD

**Issue by L-Leite** [L-Leite/cso2-master-services#22]
As the title says, should the master server and services repositories be in this repository? (cso2-master-services or cso2-master-server)

cc: @GEEKiDoS @DebugBios @organnerx

**Comment by DebugBios** [comment]
I think cso2-master-services rather than cso2-master-server would be a good way to inform the integrated problem.

**Comment by ChenyuHou** [comment]
Sounds like you will update cso2-master-services?
I think the master server and services repositories should be in this repository

**Comment by organnerx** [comment]
Depending on what are you planning to do next. In many cases I prefer to have everything in one place.
But in this case, when you have different modules, you better to not merge them and leave it as it is. They all have different ideas and functionality. The current structure is optimal for a project like this.

**Comment by L-Leite** [comment]
I was thinking on creating a new chat service, and continue splitting
whatever is left on cso2-master-server (create a channel service and
move all the user logic in here to users service).
A 12 de outubro de 2019 19:09:46 WEST, organnerx
<notifications@github.com> escreveu:

    Depending on what are you planning to do next. In many cases I
    prefer to have everything in one place.
    But in this case, when you have different modules, you better to not
    merge them and leave it as it is. They all have different ideas and
    functionality. The current structure is optimal for a project like this.

    —
    You are receiving this because you authored the thread.
    Reply to this email directly, view it on GitHub
    <https://github.com/L-Leite/cso2-master-services/issues/22?email_source=notifications&email_token=ABFZOTVAV2MAKVQZLYERJVDQOIHGVA5CNFSM4JADF752YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEBCFGSQ#issuecomment-541348682>,
    or unsubscribe

**Comment by HouTom** [comment]
I think chat service is an important function. And I prefer to have everything in one place.

**Comment by organnerx** [comment]
cso2-master-server is good for packet sending and receiving, but it is not necessary to split it in as many services, as many packets you have. I think you can leave basic services that should be in the game by default and small ones inside the master server: channels, rooms, game start; maybe even add: broadcast, daily mission, tutorial, shop. But chat system location is depend on how much code and logic it have. If you think it should be moved to a new repository then its fine.

**Comment by HouTom** [comment]
![7c14227110ac91cf](https://user-images.githubusercontent.com/45506338/66713696-8ddc6800-ede0-11e9-8e22-9eb0e5b74e2c.png)
![-2f596d1fc0eb385](https://user-images.githubusercontent.com/45506338/66713699-992f9380-ede0-11e9-8bc5-95746dce884c.png)
you can divide them into main services and user information services，and you can fix these problems on user services.
