### ISSUE TITLE
Error when building users-service and inventory-service

### ISSUE THREAD

**Issue by nvidiati422** [L-Leite/cso2-master-services#28]
/users-service/node_modules/@types/chai-json-schema/index.d.ts(28,36): error TS2694: Namespace 'Chai' has no exported member 'ChaiPlugin'.

**Comment by L-Leite** [comment]
What's your OS and nodejs version?

**Comment by L-Leite** [comment]
I have replicated this error, a fix should come out soon

**Comment by nvidiati422** [comment]
Thank you for respond, this is not the only error when I build the source code, I'm using win10 1903 and nodeJS 13.0.1.0, hope everything will be fine on next release, thank you for the great work.

**Comment by lateleite** [comment]
Fixed in https://github.com/L-Leite/cso2-users-service/commit/9bbd207 and https://github.com/L-Leite/cso2-inventory-service/commit/f5b8e10c92ff60148e151bf2b98a8cc804672238

I'm working on updating webapp and the master server to use these new versions, since their API changed
