### ISSUE TITLE
user system?

### ISSUE THREAD

**Issue by w123456w30w** [L-Leite/cso2-master-services#7]
how to add a user? or authenticate system not complete?

**Comment by Ochii** [comment]
Do an HTTP POST request to /users in your user service

Put in the request's body:
- `username` - the new user's name
- `playername` - the new user's ingame player name
- `password` - the user's account password (in plaintext)

It will return:
- status code 201 if successful
- status code 400 if you sent a bad request
- status code 409 if the user already exists (it checks for `username` and `playername`)
- status code 500 if an internal error occured

You can also see this in the [users service's documentation](https://github.com/Ochii/cso2-users-service/blob/master/docs/classes/_routes_users_.usersroute.md#private-onpostusers)
