### ISSUE TITLE
It can not use in ubuntu

### ISSUE THREAD

**Issue by HouTom** [L-Leite/cso2-master-services#8]
![wwwxx](https://user-images.githubusercontent.com/45506338/57968459-7cac3e00-799d-11e9-92f2-e03cc8014999.PNG)
ubuntu@VM-16-13-ubuntu:~/cso2-master-services$ ./setup_services.sh
-bash: ./setup_services.sh: /bin/sh^M: bad interpreter: No such file or directory

**Comment by Ochii** [comment]
Try `chmod a+x ./setup_services.sh` then execute the script again

**Comment by ChenyuHou** [comment]
![xxxx](https://user-images.githubusercontent.com/45506338/57978852-57740a00-7a47-11e9-9496-97a60dcaff2b.PNG)

**Comment by ChenyuHou** [comment]
And there was a new problem
![DO03_Q2N2%K%Z`SOJ~HK96L](https://user-images.githubusercontent.com/45506338/57978863-7b375000-7a47-11e9-8a88-b9580433fdee.png)

**Comment by L-Leite** [comment]
Sorry for being away, did you fix this? And if so, could you tell how?
